### PR TITLE
Fix move intent bug

### LINKED ISSUE #261: move intent DnD won't work
**Describe the bug**
Drag and drop intent won't work, when refreshed

**To Reproduce**
1. go to builder
2. Click on create intents many times
3. Move last intent to the first intent place, refresh
4. See error : creates new bot instead of showing builder with modified intents' list

### PR DESCRIPTION
**Pull request by jeffladiray**
*Provided via @arnaud-moncel in a rush*

# Description

**Fixes #261**

More work is needed in zoapp in order to avoid the issue seen this afternoon, but this at least should prevent major issue

## Type of change

- [x] Other (non-breaking change which doesn't match an issue, Non-code related, ...)

# How Has This Been Tested?

* Yarn/npm/nodejs version: v1.15.2/v6.4.1/v10.15.3
* OS version: macOS 10.14.5
* Chrome version: Google Chrome 74.0.3729.169 

# Checklist:

Please remove lines that are not relevant

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

File: front/src/shared/containers/explorerContainer.jsx [hunk 1]
```diff
@@ -28,6 +28,9 @@ class ExplorerContainer extends Component {
   onDropIntent = (dragIndex, dropIndex) => {
     const intent = this.props.intents[dragIndex];
     const intentId = intent.id;
+    console.log(intentId);
```
Comment (Thenkei) [inline front/src/shared/containers/explorerContainer.jsx]: You forget that @arnaud-moncel.
